[cav23]
cmd = "/root/i-Good_Lemmas_MC/nuXmv/nuXmv-ic3"
args = [
    "-a ic3 -s cadical -m 1 -u 4 -I 1 -D 0 -g 1 -X 0 -c 0 -p 1 -d 2 -G 1 -P 1 -A 100 -O 3",
    "${case}",
]

[rlive]
cmd = "/root/rlive/nuXmv"
args = ["-a", "rlive", "-sub_checker", "1", "-rlive-prune-dead", "1", "${case}"]
