name = "rIC3"
exit_code = { 10 = "Unsafe", 20 = "Safe" }

[ic3_default]
cmd = "/root/rIC3/target/release/rIC3"
args = ["-e", "ic3", "${case}"]

[ic3_inf]
cmd = "/root/rIC3/target/release/rIC3"
args = ["-e", "ic3", "${case}"]

[ic3_l2s]
cmd = "/root/rIC3/target/release/rIC3"
args = ["-e", "ic3", "${case}"]

[rlive]
cmd = "/root/rIC3/target/release/rIC3"
args = ["-e", "rlive", "${case}", "--certify"]

[portfolio]
cmd = "/root/rIC3/target/release/rIC3"
args = ["-e", "portfolio", "${case}"]
parallelism = 16
